# Generated by Django 4.1.6 on 2023-02-03 14:39

from django.db import migrations, models
import django.db.models.deletion
import menu.validators


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DishImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='menu/images', validators=[menu.validators.validate_file_size])),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='menu.dish')),
            ],
        ),
    ]
